# Smart Ops - GitHub Automation (PowerShell)
# Generated by Smart Ops Ultimate

$ErrorActionPreference = "Stop"

# ============ CONFIGURATION ============
$REPO_OWNER = "JStaRFilms"
$REPO_NAME = "jstar-fyb-service"
$REPO = "$REPO_OWNER/$REPO_NAME"

# Project Board Config (Empty strings if unused)
$PROJECT_NUMBER = ""
$PROJECT_ID = ""
$STATUS_FIELD_ID = ""
$TODO_OPTION_ID = ""
$IN_PROGRESS_OPTION_ID = ""
$DONE_OPTION_ID = ""
$START_DATE_FIELD_ID = ""
$TARGET_DATE_FIELD_ID = ""

# ============ HELPERS ============
function Write-Status { param($Msg, $Color="Cyan") Write-Host ":: $Msg" -ForegroundColor $Color }
function Get-DateStr { return (Get-Date -Format "yyyy-MM-dd") }
function Get-FutureDate { param([int]$Days); return (Get-Date).AddDays($Days).ToString("yyyy-MM-dd") }

function Invoke-GH {
    param([string[]]$Args)
    try {
        $output = gh @Args 2>&1
        if ($LASTEXITCODE -ne 0) { throw "Exit code $LASTEXITCODE" }
        return $output
    } catch {
        Write-Host "Error running: gh $($Args -join ' ')" -ForegroundColor Red
        throw
    }
}

# ============ COMMANDS ============

function Start-Scan {
    Write-Status "Scanning Active Work..."
    Invoke-GH @("issue", "list", "--repo", $REPO, "--state", "open", "--json", "number,title,labels", "--limit", "20")
    
    if (-not [string]::IsNullOrEmpty($PROJECT_NUMBER)) {
        Write-Status "`nProject Board Items:"
        try { gh project item-list $PROJECT_NUMBER --owner $REPO_OWNER --format json --limit 20 2>$null } catch {}
    }
}

function New-Issue {
    param([string]$Title, [string]$Body, [string]$Labels="enhancement", [int]$Days=7)
    
    Write-Status "Creating: $Title (Est: ${Days}d)"
    $url = Invoke-GH @("issue", "create", "--repo", $REPO, "--title", $Title, "--body", $Body, "--label", $Labels)
    
    if ($url -match '/(\d+)$') {
        $num = $Matches[1]
        Write-Host "Created Issue #$num" -ForegroundColor Green
        
        # Project Board Integration
        if (-not [string]::IsNullOrEmpty($PROJECT_ID)) {
            Write-Status "Syncing to Project Board..." "Gray"
            try {
                $itemId = gh project item-add $PROJECT_NUMBER --owner $REPO_OWNER --url $url --jq '.id'
                
                # Set Dates
                if ($START_DATE_FIELD_ID) {
                    gh project item-edit --id $itemId --project-id $PROJECT_ID --field-id $START_DATE_FIELD_ID --date (Get-DateStr) 2>$null
                }
                if ($TARGET_DATE_FIELD_ID) {
                    gh project item-edit --id $itemId --project-id $PROJECT_ID --field-id $TARGET_DATE_FIELD_ID --date (Get-FutureDate $Days) 2>$null
                }
                Write-Host "Timeline Set: $(Get-DateStr) -> $(Get-FutureDate $Days)" -ForegroundColor Gray
            } catch {
                Write-Host "Warning: Could not sync to project board." -ForegroundColor Yellow
            }
        }
    }
}

function Close-Issue {
    param([string]$Num, [string]$Comment="Completed")
    $confirm = Read-Host "Close #$Num? (y/N)"
    if ($confirm -eq 'y') {
        Invoke-GH @("issue", "close", $Num, "--repo", $REPO, "--comment", $Comment)
        Write-Host "Closed #$Num" -ForegroundColor Green
    }
}

function Move-Progress {
    param([string]$Id)
    if ($PROJECT_ID -and $Id) {
        gh project item-edit --id $Id --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $IN_PROGRESS_OPTION_ID
        if ($START_DATE_FIELD_ID) {
            gh project item-edit --id $Id --project-id $PROJECT_ID --field-id $START_DATE_FIELD_ID --date (Get-DateStr) 2>$null
        }
        Write-Host "Moved to In Progress" -ForegroundColor Green
    }
}

function Move-Done {
    param([string]$Id)
    if ($PROJECT_ID -and $Id) {
        gh project item-edit --id $Id --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $DONE_OPTION_ID
        Write-Host "Moved to Done" -ForegroundColor Green
    }
}

# ============ ROUTING ============
$cmd = if ($args.Count -gt 0) { $args[0] } else { "help" }
switch ($cmd.ToLower()) {
    "start"    { Start-Scan }
    "complete" { Start-Scan; Write-Host "`nReady to close? Use: .\scripts\smart-ops.ps1 close <number>" }
    "create"   { New-Issue $args[1] $args[2] $args[3] ([int]$args[4]) }
    "close"    { Close-Issue $args[1] $args[2] }
    "progress" { Move-Progress $args[1] }
    "done"     { Move-Done $args[1] }
    default    { Write-Host "Commands: start, complete, create, close, progress, done" }
}