#!/bin/bash
# Smart Ops - GitHub Automation (Bash)
# Generated by Smart Ops Ultimate

set -e

# ============ CONFIGURATION ============
REPO_OWNER="JStaRFilms"
REPO_NAME="jstar-fyb-service"
REPO="${REPO_OWNER}/${REPO_NAME}"

PROJECT_NUMBER="6"
PROJECT_ID="PVT_kwHOBryib84BKpDJ"
STATUS_FIELD_ID="PVTSSF_lAHOBryib84BKpDJzg6cv6I"
TODO_OPTION_ID="f75ad846"
IN_PROGRESS_OPTION_ID="47fc9ee4"
DONE_OPTION_ID="98236657"
START_DATE_FIELD_ID="PVTF_lAHOBryib84BKpDJzg6c0Vo"
TARGET_DATE_FIELD_ID="PVTF_lAHOBryib84BKpDJzg6c05U"

# ============ HELPERS ============
get_today() { date +%Y-%m-%d; }

get_future_date() {
    local days="${1:-7}"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        date -v+${days}d +%Y-%m-%d
    else
        date -d "+${days} days" +%Y-%m-%d
    fi
}

# ============ COMMANDS ============

start() {
    echo "🔍 Scanning active work..."
    gh issue list --repo "$REPO" --state open --json number,title,labels --limit 20
    if [ -n "$PROJECT_NUMBER" ]; then
        echo ""
        gh project item-list "$PROJECT_NUMBER" --owner "$REPO_OWNER" --format json --limit 20 2>/dev/null || true
    fi
}

create_issue() {
    local title="$1"
    local body="$2"
    local labels="${3:-enhancement}"
    local days="${4:-7}"
    
    echo "📝 Creating: $title ($days days)"
    local url=$(gh issue create --repo "$REPO" --title "$title" --body "$body" --label "$labels")
    local num=$(echo "$url" | grep -oE '[0-9]+$')
    
    echo "✅ Created #$num"
    
    if [ -n "$PROJECT_ID" ]; then
        local item_id=$(gh project item-add "$PROJECT_NUMBER" --owner "$REPO_OWNER" --url "$url" --jq '.id')
        
        [ -n "$START_DATE_FIELD_ID" ] && \
            gh project item-edit --id "$item_id" --project-id "$PROJECT_ID" --field-id "$START_DATE_FIELD_ID" --date "$(get_today)" 2>/dev/null
        
        [ -n "$TARGET_DATE_FIELD_ID" ] && \
            gh project item-edit --id "$item_id" --project-id "$PROJECT_ID" --field-id "$TARGET_DATE_FIELD_ID" --date "$(get_future_date "$days")" 2>/dev/null
            
        echo "📅 Timeline set"
    fi
}

close_issue() {
    local num="$1"
    local comment="${2:-Completed}"
    read -p "Close #$num? (y/N): " -n 1 -r; echo
    [[ $REPLY =~ ^[Yy]$ ]] && gh issue close "$num" --repo "$REPO" --comment "$comment" && echo "✅ Closed #$num"
}

move_progress() {
    [ -n "$PROJECT_ID" ] && gh project item-edit --id "$1" --field-id "$STATUS_FIELD_ID" --project-id "$PROJECT_ID" --single-select-option-id "$IN_PROGRESS_OPTION_ID"
    [ -n "$START_DATE_FIELD_ID" ] && gh project item-edit --id "$1" --project-id "$PROJECT_ID" --field-id "$START_DATE_FIELD_ID" --date "$(get_today)" 2>/dev/null
    echo "→ In Progress"
}

move_done() {
    [ -n "$PROJECT_ID" ] && gh project item-edit --id "$1" --field-id "$STATUS_FIELD_ID" --project-id "$PROJECT_ID" --single-select-option-id "$DONE_OPTION_ID"
    echo "→ Done"
}

# ============ ROUTING ============
case "${1:-help}" in
    start) start ;;
    complete) start; echo ""; echo "Close with: ./scripts/smart-ops.sh close <number>" ;;
    create) create_issue "$2" "$3" "$4" "$5" ;;
    close) close_issue "$2" "$3" ;;
    progress) move_progress "$2" ;;
    done) move_done "$2" ;;
    *) echo "Usage: start, complete, create, close, progress, done" ;;
esac