# Smart Ops - GitHub Automation Script (PowerShell)
# Generated by /init_smart_ops workflow

$ErrorActionPreference = "Stop"

# ============ CONFIGURATION ============
$REPO_OWNER = "JStaRFilms"
$REPO_NAME = "jstar-fyb-service"
$REPO = "$REPO_OWNER/$REPO_NAME"

$PROJECT_NUMBER = ""
$PROJECT_ID = ""
$STATUS_FIELD_ID = ""
$TODO_OPTION_ID = ""
$IN_PROGRESS_OPTION_ID = ""
$DONE_OPTION_ID = ""

$START_DATE_FIELD_ID = ""
$TARGET_DATE_FIELD_ID = ""

$DEBUG = $env:DEBUG -eq "1"

# ============ PREREQUISITES ============

function Test-Prerequisites {
    $errors = 0
    
    try { $null = Get-Command gh -ErrorAction Stop }
    catch {
        Write-Host "X GitHub CLI not installed: https://cli.github.com" -ForegroundColor Red
        $errors++
    }
    
    try {
        $null = gh auth status 2>&1
        if ($LASTEXITCODE -ne 0) { throw }
    } catch {
        Write-Host "X Not authenticated. Run: gh auth login" -ForegroundColor Red
        $errors++
    }
    
    if ([string]::IsNullOrWhiteSpace($REPO_OWNER) -or [string]::IsNullOrWhiteSpace($REPO_NAME)) {
        Write-Host "X REPO_OWNER and REPO_NAME must be set" -ForegroundColor Red
        $errors++
    }
    
    if ($errors -gt 0) { exit 1 }
}

# ============ HELPERS ============

function Write-Debug { param([string]$Msg) if ($DEBUG) { Write-Host "[DEBUG] $Msg" -ForegroundColor Gray } }
function Write-Err { param([string]$Msg) Write-Host "X $Msg" -ForegroundColor Red }
function Write-Ok { param([string]$Msg) Write-Host "✓ $Msg" -ForegroundColor Green }

function Get-Today { return (Get-Date -Format "yyyy-MM-dd") }
function Get-FutureDate { param([int]$Days = 7); return (Get-Date).AddDays($Days).ToString("yyyy-MM-dd") }

function Invoke-GH {
    param([string[]]$Args)
    Write-Debug "gh $($Args -join ' ')"
    try {
        $output = gh @Args 2>&1
        if ($LASTEXITCODE -ne 0) { throw "Exit code $LASTEXITCODE" }
        return $output
    } catch {
        Write-Err "Command failed: gh $($Args -join ' ')"
        throw
    }
}

# ============ COMMANDS ============

function Start-Scan {
    Write-Host "Scanning work..." -ForegroundColor Cyan
    Invoke-GH @("issue", "list", "--repo", $REPO, "--state", "open", "--json", "number,title,labels", "--limit", "20")
    
    if (![string]::IsNullOrWhiteSpace($PROJECT_NUMBER)) {
        Write-Host ""
        try { gh project item-list $PROJECT_NUMBER --owner $REPO_OWNER --format json --limit 20 2>$null }
        catch { }
    }
}

function Complete-Scan {
    Write-Host "Ready for completion..." -ForegroundColor Cyan
    Invoke-GH @("issue", "list", "--repo", $REPO, "--state", "open", "--json", "number,title", "--limit", "20")
    Write-Host ""
    Write-Host "Today: $(Get-Today)"
    Write-Host 'Close with: .\scripts\smart-ops.ps1 close [number]' -ForegroundColor Gray
}

function New-Issue {
    param(
        [string]$Title,
        [string]$Body = "",
        [string]$Labels = "enhancement",
        [int]$Days = 7
    )
    
    if ([string]::IsNullOrWhiteSpace($Title)) {
        Write-Err "Title required"
        return
    }
    
    Write-Host "Creating: $Title (${Days}d)" -ForegroundColor Cyan
    
    $url = Invoke-GH @("issue", "create", "--repo", $REPO, "--title", $Title, "--body", $Body, "--label", $Labels)
    
    if ($url -match '/(\d+)$') {
        $num = $Matches[1]
        Write-Ok "Created #$num"
        
        if (![string]::IsNullOrWhiteSpace($PROJECT_ID)) {
            try {
                $itemId = gh project item-add $PROJECT_NUMBER --owner $REPO_OWNER --url $url --jq '.id'
                
                if (![string]::IsNullOrWhiteSpace($START_DATE_FIELD_ID)) {
                    gh project item-edit --id $itemId --project-id $PROJECT_ID --field-id $START_DATE_FIELD_ID --date (Get-Today) 2>$null
                }
                if (![string]::IsNullOrWhiteSpace($TARGET_DATE_FIELD_ID)) {
                    gh project item-edit --id $itemId --project-id $PROJECT_ID --field-id $TARGET_DATE_FIELD_ID --date (Get-FutureDate -Days $Days) 2>$null
                }
                Write-Ok "Added to project"
            } catch {
                Write-Err "Failed to add to project"
            }
        }
        Write-Host $url
    }
}

function Close-Issue {
    param([string]$Num, [string]$Comment = "Completed")
    
    if ([string]::IsNullOrWhiteSpace($Num)) {
        Write-Err "Issue number required"
        return
    }
    
    $confirm = Read-Host "Close #${Num}? (y/N)"
    if ($confirm -ne 'y') { return }
    
    Invoke-GH @("issue", "close", $Num, "--repo", $REPO, "--comment", $Comment)
    Write-Ok "Closed #$Num"
}

function Move-ToProgress {
    param([string]$Id)
    
    if ([string]::IsNullOrWhiteSpace($PROJECT_ID)) {
        Write-Err "No project configured"
        return
    }
    if ([string]::IsNullOrWhiteSpace($Id)) {
        Write-Err "Item ID required"
        return
    }
    
    gh project item-edit --id $Id --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $IN_PROGRESS_OPTION_ID
    
    if (![string]::IsNullOrWhiteSpace($START_DATE_FIELD_ID)) {
        gh project item-edit --id $Id --project-id $PROJECT_ID --field-id $START_DATE_FIELD_ID --date (Get-Today) 2>$null
    }
    Write-Ok "-> In Progress"
}

function Move-ToDone {
    param([string]$Id)
    
    if ([string]::IsNullOrWhiteSpace($PROJECT_ID)) {
        Write-Err "No project configured"
        return
    }
    if ([string]::IsNullOrWhiteSpace($Id)) {
        Write-Err "Item ID required"
        return
    }
    
    gh project item-edit --id $Id --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $DONE_OPTION_ID
    Write-Ok "-> Done"
}

function Show-Help {
    Write-Host @'
Smart Ops - GitHub Automation

Usage: .\scripts\smart-ops.ps1 [command] [args]

Commands:
  start                      List open issues
  complete                   List for completion
  create [title] [body] [labels] [days]
  close [number] [comment]
  progress [item_id]         Move to In Progress
  done [item_id]             Move to Done

Examples:
  .\scripts\smart-ops.ps1 create "Fix bug" "Description" "bug" 3
  .\scripts\smart-ops.ps1 close 42 "Fixed"
  $env:DEBUG=1; .\scripts\smart-ops.ps1 start
'@ -ForegroundColor Cyan
}

# ============ MAIN ============

Test-Prerequisites

$cmd = if ($args.Count -gt 0) { $args[0] } else { "help" }

try {
    switch ($cmd.ToLower()) {
        "start" { Start-Scan }
        "complete" { Complete-Scan }
        "create" { New-Issue -Title $args[1] -Body $args[2] -Labels $args[3] -Days ([int]$args[4]) }
        "close" { Close-Issue -Num $args[1] -Comment $args[2] }
        "progress" { Move-ToProgress -Id $args[1] }
        "done" { Move-ToDone -Id $args[1] }
        default { Show-Help }
    }
} catch {
    Write-Host ""
    Write-Err "Failed: $_"
    exit 1
}