#!/bin/bash
# Smart Ops - GitHub Automation Script
# Generated by /init_smart_ops workflow

set -e

# ============ CONFIGURATION ============
REPO_OWNER="JStaRFilms"
REPO_NAME="jstar-fyb-service"
REPO="${REPO_OWNER}/${REPO_NAME}"

PROJECT_NUMBER=""
PROJECT_ID=""
STATUS_FIELD_ID=""
TODO_OPTION_ID=""
IN_PROGRESS_OPTION_ID=""
DONE_OPTION_ID=""

START_DATE_FIELD_ID=""
TARGET_DATE_FIELD_ID=""

DEBUG="${DEBUG:-0}"

# ============ PREREQUISITES ============

check_prerequisites() {
    local errors=0
    
    if ! command -v gh &> /dev/null; then
        echo "❌ GitHub CLI not installed: https://cli.github.com" >&2
        errors=$((errors + 1))
    fi
    
    if ! gh auth status &> /dev/null; then
        echo "❌ Not authenticated. Run: gh auth login" >&2
        errors=$((errors + 1))
    fi
    
    if [ -z "$REPO_OWNER" ] || [ -z "$REPO_NAME" ]; then
        echo "❌ REPO_OWNER and REPO_NAME must be set" >&2
        errors=$((errors + 1))
    fi
    
    [ "$errors" -gt 0 ] && exit 1
}

# ============ HELPERS ============

log_debug() { [ "$DEBUG" = "1" ] && echo "[DEBUG] $*" >&2; }
log_error() { echo "❌ $*" >&2; }
log_success() { echo "✅ $*"; }

get_today() { date +%Y-%m-%d; }

get_future_date() {
    local days="${1:-7}"
    if [[ "$OSTYPE" == "darwin"* ]]; then
        date -v+${days}d +%Y-%m-%d
    else
        date -d "+${days} days" +%Y-%m-%d
    fi
}

gh_safe() {
    log_debug "gh $*"
    if output=$(gh "$@" 2>&1); then
        echo "$output"
        return 0
    else
        log_error "Command failed: gh $*"
        return 1
    fi
}

# ============ COMMANDS ============

start() {
    echo "🔍 Scanning active work..."
    echo ""
    gh_safe issue list --repo "$REPO" --state open --json number,title,labels --limit 20 || return 1
    
    if [ -n "$PROJECT_NUMBER" ]; then
        echo ""
        gh project item-list "$PROJECT_NUMBER" --owner "$REPO_OWNER" --format json --limit 20 2>/dev/null || true
    fi
}

complete() {
    echo "📋 Issues ready for completion..."
    gh_safe issue list --repo "$REPO" --state open --json number,title --limit 20 || return 1
    echo ""
    echo "Today: $(get_today)"
    echo "Close with: ./smart-ops.sh close <number>"
}

create_issue() {
    local title="$1"
    local body="$2"
    local labels="${3:-enhancement}"
    local days="${4:-7}"
    
    [ -z "$title" ] && { log_error "Title required"; return 1; }
    
    echo "📝 Creating: $title (${days}d)"
    
    local url
    url=$(gh_safe issue create --repo "$REPO" --title "$title" --body "$body" --label "$labels") || return 1
    
    local num
    num=$(echo "$url" | grep -oE '[0-9]+$')
    [ -z "$num" ] && { log_error "Failed to parse issue number"; return 1; }
    
    log_success "Created #$num"
    
    if [ -n "$PROJECT_ID" ]; then
        local item_id
        item_id=$(gh_safe project item-add "$PROJECT_NUMBER" --owner "$REPO_OWNER" --url "$url" --jq '.id') || {
            log_error "Failed to add to project"
            echo "$url"
            return 0
        }
        
        [ -n "$START_DATE_FIELD_ID" ] && \
            gh project item-edit --id "$item_id" --project-id "$PROJECT_ID" \
                --field-id "$START_DATE_FIELD_ID" --date "$(get_today)" 2>/dev/null || true
        
        [ -n "$TARGET_DATE_FIELD_ID" ] && \
            gh project item-edit --id "$item_id" --project-id "$PROJECT_ID" \
                --field-id "$TARGET_DATE_FIELD_ID" --date "$(get_future_date "$days")" 2>/dev/null || true
        
        log_success "Added to project"
    fi
    
    echo "$url"
}

close_issue() {
    local num="$1"
    local comment="${2:-Completed on $(get_today)}"
    
    [ -z "$num" ] && { log_error "Issue number required"; return 1; }
    
    read -p "Close #$num? (y/N): " -n 1 -r; echo
    [[ ! $REPLY =~ ^[Yy]$ ]] && return 0
    
    gh_safe issue close "$num" --repo "$REPO" --comment "$comment" || return 1
    log_success "Closed #$num"
}

move_to_in_progress() {
    local id="$1"
    [ -z "$PROJECT_ID" ] && { log_error "No project configured"; return 1; }
    [ -z "$id" ] && { log_error "Item ID required"; return 1; }
    
    gh project item-edit --id "$id" --field-id "$STATUS_FIELD_ID" \
        --project-id "$PROJECT_ID" --single-select-option-id "$IN_PROGRESS_OPTION_ID" || return 1
    
    [ -n "$START_DATE_FIELD_ID" ] && \
        gh project item-edit --id "$id" --project-id "$PROJECT_ID" \
            --field-id "$START_DATE_FIELD_ID" --date "$(get_today)" 2>/dev/null || true
    
    log_success "→ In Progress"
}

move_to_done() {
    local id="$1"
    [ -z "$PROJECT_ID" ] && { log_error "No project configured"; return 1; }
    [ -z "$id" ] && { log_error "Item ID required"; return 1; }
    
    gh project item-edit --id "$id" --field-id "$STATUS_FIELD_ID" \
        --project-id "$PROJECT_ID" --single-select-option-id "$DONE_OPTION_ID" || return 1
    
    log_success "→ Done"
}

show_help() {
    cat << 'EOF'
Smart Ops - GitHub Automation

Usage: ./smart-ops.sh <command> [args]

Commands:
  start                      List open issues
  complete                   List for completion
  create <title> [body] [labels] [days]
  close <number> [comment]
  progress <item_id>         Move to In Progress
  done <item_id>             Move to Done

Examples:
  ./smart-ops.sh create "Fix bug" "Description" "bug" 3
  ./smart-ops.sh close 42 "Fixed"
  DEBUG=1 ./smart-ops.sh start
EOF
}

# ============ MAIN ============

check_prerequisites

case "${1:-help}" in
    start) start ;;
    complete) complete ;;
    create) create_issue "$2" "$3" "$4" "$5" ;;
    close) close_issue "$2" "$3" ;;
    progress) move_to_in_progress "$2" ;;
    done) move_to_done "$2" ;;
    *) show_help ;;
esac